---
- hosts: webservers
  become: true
  tasks:
    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Start and enable Apache service
      service:
        name: apache2
        state: stopped
        enabled: true

    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/index.html
